config/routes.rb
TranscationDemo::Application.routes.draw do
  resources :transcations

  devise_for :users

  get "home/welcome"

 root :to => 'home#index'

end

app/models/transcation.rb
class Transcation < ActiveRecord::Base
  attr_accessible :amount, :title, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :transcations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(resource)

  home_welcome_path

end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def welcome
  end
end

app/controllers/transcations_controller.rb
class TranscationsController < ApplicationController
  # GET /transcations
  # GET /transcations.json
  def index
    @transcations = Transcation.all
@transaction_sums = current_user.transcations.select("created_at, SUM(amount) as amount").group("date(created_at)").order('created_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transcations }
    end
  end

  # GET /transcations/1
  # GET /transcations/1.json
  def show
  
    @transcation = Transcation.find(params[:id])
    
    #   @transcation_dc= Transcation.all(:select => "created_at, SUM(amount) amount",:group => "DATE(created_at)", :order => "created_at") 
  

  
  
          


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transcation }
    end
  end

  # GET /transcations/new
  # GET /transcations/new.json
  def new
    @transcation = Transcation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transcation }
    end
  end

  # GET /transcations/1/edit
  def edit
    @transcation = Transcation.find(params[:id])
  end

  # POST /transcations
  # POST /transcations.json
  def create
    
    @transcation = current_user.transcations.create(:amount => params[:transcation][:amount], :title => params[:transcation][:title])

    respond_to do |format|
      if @transcation.save
        format.html { redirect_to @transcation, notice: 'Transcation was successfully created.' }
        format.json { render json: @transcation, status: :created, location: @transcation }
      else
        format.html { render action: "new" }
        format.json { render json: @transcation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transcations/1
  # PUT /transcations/1.json
  def update
    @transcation = Transcation.find(params[:id])

    respond_to do |format|
      if @transcation.update_attributes(params[:transcation])
        format.html { redirect_to @transcation, notice: 'Transcation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transcation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transcations/1
  # DELETE /transcations/1.json
  def destroy
    @transcation = Transcation.find(params[:id])
    @transcation.destroy

    respond_to do |format|
      format.html { redirect_to transcations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transcations_helper.rb
module TranscationsHelper
end

app/views/home/index.html.erb
<h1>index</h1>

<%= link_to "Next",home_welcome_path%>

app/views/home/welcome.html.erb
<h1>welcome page</h1></br>
<%= link_to "create_transcation",transcations_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TranscationDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if !user_signed_in? %>
		<%= link_to "sign_in" , new_user_session_path%>
	<% else %>
		<%= link_to "sign_out" , destroy_user_session_path,:method => :delete %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/transcations/_form.html.erb
<%= form_for(@transcation) do |f| %>
  <% if @transcation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transcation.errors.count, "error") %> prohibited this transcation from being saved:</h2>

      <ul>
      <% @transcation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transcations/edit.html.erb
<h1>Editing transcation</h1>

<%= render 'form' %>

<%= link_to 'Show', @transcation %> |
<%= link_to 'Back', transcations_path %>

app/views/transcations/index.html.erb
<h1>Listing transcations</h1>

<table>
  <tr>
    <th>Amount</th>
    <th></th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @transcations.each do |transcation| %>
  <tr>
    <td><%= transcation.amount %></td>
    
    <td><%= transcation.title %></td>
    
    <td><%= link_to 'Show', transcation %></td>
    <td><%= link_to 'Edit', edit_transcation_path(transcation) %></td>
    <td><%= link_to 'Destroy', transcation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

<tr>
    <th>Transcation_amount</th>
    <th></th>
    <th>date</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</table>


<% @transaction_sums.each do |transaction_sum| %>
  <tr>
    <td><%= transaction_sum.amount %></td>
    
    <td><%= transaction_sum.created_at %></td>
    
    
  </tr>
  <br />
<% end %>




<%= link_to 'New Transcation', new_transcation_path %>

app/views/transcations/new.html.erb
<h1>New transcation</h1>

<%= render 'form' %>

<%= link_to 'Back', transcations_path %>

app/views/transcations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @transcation.amount %>
</p>


<p>
  <b>Title:</b>
  <%= @transcation.title %>
</p>




<%= link_to 'Edit', edit_transcation_path(@transcation) %> |
<%= link_to 'Back', transcations_path %>